FROM lmsysorg/sglang:v0.5.5.post3

COPY python/sglang/srt/server_args.py /sgl-workspace/sglang/python/sglang/srt/server_args.py
COPY python/sglang/srt/models/qwen3_vl.py /sgl-workspace/sglang/python/sglang/srt/models/qwen3_vl.py

CMD ["/bin/bash"]
