FROM lmsysorg/sglang:v0.5.9

ARG SGLANG_PATH="/sgl-workspace/sglang/python/sglang"

COPY python/sglang/srt/entrypoints/openai/serving_chat.py ${SGLANG_PATH}/srt/entrypoints/openai/serving_chat.py

CMD ["/bin/bash"]